### ISSUE TITLE
Python packages

### ISSUE THREAD

**Issue by davetang** [jon-xu/scSplit#1]
I'm trying to install the list of packages listed in your README using conda. However, there are several packages that cannot be found.

```
ResolvePackageNotFound: 
  - pickle
  - vcf
  - random
  - math
  - sklearn
```

I guess the `pickle`, `math`, and `random` packages are part of the standard library. As for the other packages, did you mean `scikit-learn` for `sklearn` and `vcftools` for `vcf`?

**Comment by davetang** [comment]
In addition, I can't install the `statistics` package using Python version 3.6.

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.6
  - statistics -> python[version='>=2.7,<2.8.0a0']
```

**Comment by jon-xu** [comment]
Hi Dave,

Sorry for the late reply!

Yes, please install scikit-learn and PyVCF.
And statistics module is part of python3 standard library, you don't need to install it.

Thanks for pointing it out and I'll make it clear in the README.

**Comment by jon-xu** [comment]
@davetang have you been successful on this?  Please feel free let me know if any other issues.
