### ISSUE TITLE
Pileup error

### ISSUE THREAD

**Issue by drneavin** [jon-xu/scSplit#11]
Hi Jon,

I have received this error when recently trying to use scSplit at the allele pileup step:

```
Traceback (most recent call last):
  File "/opt/scSplit/scSplit", line 695, in <module>
    scSplit()
  File "/opt/scSplit/scSplit", line 357, in __init__
    getattr(self, args.command)()
  File "/opt/scSplit/scSplit", line 450, in count
    for line in open(args.bar, 'r'):
  File "/usr/local/envs/py36/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
```

I have a sneaking suspicion that it is because version 3 of cellranger outputs a gzipped barcode file. Any chance you could add a couple lines in to deal with the possibility of gzipped barcode files? Let me know if you think that there is something else going on here.

Thanks,
Drew

**Comment by jon-xu** [comment]
Hi Drew,

Thanks for pointing it out.
I've added the support for gzipped barcode files.

Cheers,
Jon
