### ISSUE TITLE
Possibility to use for sc/snATAC-seq?

### ISSUE THREAD

**Issue by ah3918** [jon-xu/scSplit#12]
Hi, 

I hope this finds you well. Not an issue per se, but I was wondering whether you had explored or considered the use of scSplit for demultiplexing pooled samples in scATAC-seq (or snATAC-seq), specifically 10X data?

Thanks!

**Comment by jon-xu** [comment]
Hi,
Thanks for the question - it's an interesting idea!
Unfortunately we didn't test this tool on sc/snATAC-seq yet, although theoretically it should be possible.
Cheers
