### ISSUE TITLE
Memory error, which can be fixed

### ISSUE THREAD

**Issue by VladimirShitov** [jon-xu/scSplit#13]
There are 2 pandas DataFrames being created in `build_base_call_matrix()`. However, their type is not explicitly set. Pandas sets it to `np.int64` by default, which causes a huge amount of memory to be allocated. For big matrices it causes MemoryError:
![Screenshot from 2021-01-16 20-53-34](https://user-images.githubusercontent.com/35199218/104832503-1c814400-58c4-11eb-9075-fde5f6c30e05.png)

I'm not sure, how big numbers in the matrices can be. But I believe, `np.int16` would be more than enough. Please, set the type that matches the task.

**Comment by jon-xu** [comment]
Thanks for the suggestion!
Corrected in the newest release.
