### ISSUE TITLE
scSplit ends silently

### ISSUE THREAD

**Issue by achernom** [jon-xu/scSplit#16]
Hi, I am trying to run scSplit on snRNA seq mouse data.
Unfortunately the program ends unexpectedly (no output files ) without any error nor warning messages.
Here is my command-line:
`~/Downloads/scSplit/scSplit counts -v DG-003-filt.vcf.gz -i DG-003_S2/filteredBAMforPileUp.bam -b 3M-february-2018.txt --tag CR  -r ref_filtered.csv -a alt_filtered.csv -o results`

Perhaps I should mention that  I installed the required packages using pip3 (I am not a python user), but I got some weird linker messages that appeared after  `import vcf`:
`>>>import vcf
Error: package or namespace load failred for "methods" in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object ¨/usr/local/lib/R/library/methods/libs/methods.so":
  libR.so: cannot open shared object file: No such file or directory`

After setting the environmental LD_LIBRARY_PATH variable the error dissapeared.
Any help will be very wellcome!
Ariel

**Comment by jon-xu** [comment]
Hi Ariel,
Could you try gunzip your vcf file first before counting?
Jon

**Comment by achernom** [comment]
Hi Jon,
Thanks for your prompt response.
The problem persists with the plain text vcf
A

**Comment by jon-xu** [comment]
Hi Ariel,

Did you use the barcode whitelist downloaded from 10x website? That's the full whitelist from 10x experiments.
Here you need to use the barcode list from the result of your 10x cellranger run (filtered one).

Hope it helps.
Jon

**Comment by achernom** [comment]
Hi Jon,
Just to close this issue...I found the cause of the problem ... I was invoking scSplit using `scSplit counts` instead of `scSplit count` (ay!). Anyway...thanks for your support
Ariel
