### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str`

### ISSUE THREAD

**Issue by Griffan** [jon-xu/scSplit#2]
`Traceback (most recent call last):
  File "../main.py", line 359, in <module>
    main()
  File "../main.py", line 296, in main
    num = args.num + 1  # additional doublet state
TypeError: can only concatenate str (not "int") to str`

I am using python 3, previous steps finished smoothly, could you help check this error?

**Comment by jon-xu** [comment]
Sorry saw this late, it has been fixed in the newest update.

**Comment by jon-xu** [comment]
@Griffan please let me know should you still have this issue.

**Comment by Griffan** [comment]
yes, it is resolved.

**Comment by jon-xu** [comment]
Thanks!
