### ISSUE TITLE
Load time error

### ISSUE THREAD

**Issue by abmmki** [jon-xu/scSplit#23]
scSplit -h

R[write to console]: Error: package or namespace load failed for ‘methods’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib64/R/library/methods/libs/methods.so':
  /usr/local/lib64/R/library/methods/libs/methods.so: undefined symbol: Rf_allocS4Object

R[write to console]: Error: package or namespace load failed for ‘utils’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib64/R/library/utils/libs/utils.so':
  /usr/local/lib64/R/library/utils/libs/utils.so: undefined symbol: R_NilValue

R[write to console]: Error: package or namespace load failed for ‘grDevices’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib64/R/library/grDevices/libs/grDevices.so':
  /usr/local/lib64/R/library/grDevices/libs/grDevices.so: undefined symbol: R_NilValue

R[write to console]: Error: package or namespace load failed for ‘graphics’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib64/R/library/grDevices/libs/grDevices.so':
  /usr/local/lib64/R/library/grDevices/libs/grDevices.so: undefined symbol: R_NilValue

R[write to console]: Error: package or namespace load failed for ‘stats’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib64/R/library/grDevices/libs/grDevices.so':
  /usr/local/lib64/R/library/grDevices/libs/grDevices.so: undefined symbol: R_NilValue

R[write to console]: Error: package or namespace load failed for ‘methods’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib64/R/library/methods/libs/methods.so':
  /usr/local/lib64/R/library/methods/libs/methods.so: undefined symbol: Rf_allocS4Object

R[write to console]: During startup - 
R[write to console]: Warning messages:

R[write to console]: 1: package "methods" in options("defaultPackages") was not found 

R[write to console]: 2: package ‘utils’ in options("defaultPackages") was not found 

R[write to console]: 3: package ‘grDevices’ in options("defaultPackages") was not found 

R[write to console]: 4: package ‘graphics’ in options("defaultPackages") was not found 

R[write to console]: 5: package ‘stats’ in options("defaultPackages") was not found 

R[write to console]: 6: package ‘methods’ in options("defaultPackages") was not found 

R[write to console]: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib64/R/library/methods/libs/methods.so':
  /usr/local/lib64/R/library/methods/libs/methods.so: undefined symbol: Rf_allocS4Object

usage: scSplit <command> [<args>]

Commands:
   count     Generate REF/ALT count matrices from pooled BAM file
   run       Demultiplex the scRNA-Seq using REF/ALT count matrices
   genotype  Generate sample genotypes in VCF format

How to solve this?
 Using Fedora, Python 3.6. All python module installed. Also all R packages.

**Comment by jon-xu** [comment]
scSplit doesn't use any R package.

Please test in your platform all the below python modules can be imported properly:

import numpy as np
import pysam as ps
import pandas as pd
import statistics as stat
from scipy.stats import binom
from scipy.sparse import csr_matrix
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import sys, io, vcf, csv, math, datetime, pickle, argparse

**Comment by abmmki** [comment]
Hi,

It is the module vcf that is creating problem. It installed successfully:

pip install PyVCF

Then we import vcf module  in python:

python3
Python 3.7.7 (default, Mar 13 2020, 21:39:43) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vcf
R[write to console]: Error: package or namespace load failed for ‘methods’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib64/R/library/methods/libs/methods.so':
  /usr/local/lib64/R/library/methods/libs/methods.so: undefined symbol: Rf_allocS4Object

R[write to console]: Error: package or namespace load failed for ‘utils’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib64/R/library/utils/libs/utils.so':
  /usr/local/lib64/R/library/utils/libs/utils.so: undefined symbol: R_NilValue

R[write to console]: Error: package or namespace load failed for ‘grDevices’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib64/R/library/grDevices/libs/grDevices.so':
  /usr/local/lib64/R/library/grDevices/libs/grDevices.so: undefined symbol: R_NilValue

R[write to console]: Error: package or namespace load failed for ‘graphics’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib64/R/library/grDevices/libs/grDevices.so':
  /usr/local/lib64/R/library/grDevices/libs/grDevices.so: undefined symbol: R_NilValue

R[write to console]: Error: package or namespace load failed for ‘stats’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib64/R/library/grDevices/libs/grDevices.so':
  /usr/local/lib64/R/library/grDevices/libs/grDevices.so: undefined symbol: R_NilValue

R[write to console]: Error: package or namespace load failed for ‘methods’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib64/R/library/methods/libs/methods.so':
  /usr/local/lib64/R/library/methods/libs/methods.so: undefined symbol: Rf_allocS4Object

R[write to console]: During startup - 
R[write to console]: Warning messages:

R[write to console]: 1: package "methods" in options("defaultPackages") was not found 

R[write to console]: 2: package ‘utils’ in options("defaultPackages") was not found 

R[write to console]: 3: package ‘grDevices’ in options("defaultPackages") was not found 

R[write to console]: 4: package ‘graphics’ in options("defaultPackages") was not found 

R[write to console]: 5: package ‘stats’ in options("defaultPackages") was not found 

R[write to console]: 6: package ‘methods’ in options("defaultPackages") was not found 

R[write to console]: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib64/R/library/methods/libs/methods.so':
  /usr/local/lib64/R/library/methods/libs/methods.so: undefined symbol: Rf_allocS4Object

**Comment by jon-xu** [comment]
Thanks for the update!
In this case, I would think the best is to check with PyVCF team.
Hope it will be resolved soon!
