### ISSUE TITLE
syntax error in scSplit count

### ISSUE THREAD

**Issue by jagregory17** [jon-xu/scSplit#5]
Hello, 

I'm a running python 3.7 and created an environment with the appropriate modules so it can later be called when submitting a job to the cluster for scSplit count. I'm having trouble building the account matrices though.

 packages in environment at /PATHtoENV/conda/scSplit-env:

blas                      1.0                         mkl  
certifi                   2016.2.28                py27_0  
docutils                  0.15.2                   py27_0    conda-forge
libgfortran               3.0.0                         1  
mkl                       2017.0.3                      0  
numpy                     1.13.1                   py27_0  
openssl                   1.0.2l                        0  
pandas                    0.20.3                   py27_0  
pip                       9.0.1                    py27_1  
pysam                     0.6                      py27_0  
python                    2.7.13                        0  
python-dateutil           2.6.1                    py27_0  
pytz                      2017.2                   py27_0  
pyvcf                     0.6.8                 py27_1000    conda-forge
readline                  6.2                           2  
scikit-learn              0.19.0              np113py27_0  
scipy                     0.19.1              np113py27_0  
setuptools                36.4.0                   py27_1  
six                       1.10.0                   py27_0  
sqlite                    3.13.0                        0  
statistics                1.0.3.5                 py_1002    conda-forge
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
zlib                      1.2.11                        0  

the following command throws a syntax error:
 
python /PathToscript/scSplit/scSplit count \
        -v $mixedvcf \
        -i $filteredbam \
        -b $barcodes \
        -r ${BASEDIR}/ref_filtered.csv \
        -a ${BASEDIR}/alt_filtered.csv

I'm getting the following error:

 File "/pathtoscript/github/scSplit/scSplit", line 104
    rows, cols = [*range(base_mtx.shape[0])], [*range(base_mtx.shape[1])]
                  ^
SyntaxError: invalid syntax

The comments immediately preceding this command refer to the barcodes:

find barcodes for state initialization, using subsetting/PCA/K-mean

as far as I can tell the barcodes.tsv is fine and the path is correct. Any suggestions?

**Comment by jon-xu** [comment]
Hi Jagregory17,

Thanks for your interest on scSplit!

Are you sure you are running in Python 3.7? - I just re-tested in Python 3.7.4, it seems fine.

Cheers,
Jon

**Comment by jon-xu** [comment]
Hi Jagregory17,

Are you sure you are running on Python 3.7? - It seems like a syntax error from Python 2.7.

Would you mind checking again and letting me know?

Cheers,
Jon

**Comment by jagregory17** [comment]
I think you are right. despite having loaded python 3.7, it was using version 2.7 when checked the version of python from within the bash script. I think i must have created the conda environment with the default python version on the cluster, and so when i activated that environment it loaded python 2.7. Thanks so much!

**Comment by jon-xu** [comment]
Great to know!  Feel free if there is any other issues.

I'll close this one.
Cheers,
Jon
